# Generated by Django 5.2.9 on 2025-12-10 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.CharField(choices=[('cardio', 'Кардио'), ('strength', 'Силовая'), ('yoga', 'Йога/Растяжка')], max_length=20, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('want_cardio', models.BooleanField(default=True, verbose_name='Хочу Кардио')),
                ('want_strength', models.BooleanField(default=True, verbose_name='Хочу Силовые')),
                ('want_yoga', models.BooleanField(default=True, verbose_name='Хочу Йогу')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
